using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cqrs.SourceGenerator;

/// <summary>
/// Emits a reflection-free <c>IDispatcher</c> implementation and DI registration extension by
/// scanning the compilation for types implementing <c>ICommandHandler&lt;,&gt;</c> / <c>IQueryHandler&lt;,&gt;</c>.
/// Replaces the previous runtime reflection-based dispatcher (MakeGenericType + MethodInfo.Invoke).
/// </summary>
[Generator]
public sealed class DispatcherGenerator : IIncrementalGenerator
{
    private const string CommandHandlerMetadataName = "Application.CQRS.ICommandHandler`2";
    private const string QueryHandlerMetadataName = "Application.CQRS.IQueryHandler`2";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol?> candidateClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 },
                transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null);

        IncrementalValueProvider<(Compilation Compilation, ImmutableArray<INamedTypeSymbol?> Candidates)> compilationAndClasses =
            context.CompilationProvider.Combine(candidateClasses.Collect());

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Compilation, source.Candidates, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol?> candidates, SourceProductionContext context)
    {
        INamedTypeSymbol? commandHandlerInterface = compilation.GetTypeByMetadataName(CommandHandlerMetadataName);
        INamedTypeSymbol? queryHandlerInterface = compilation.GetTypeByMetadataName(QueryHandlerMetadataName);

        if (commandHandlerInterface is null || queryHandlerInterface is null)
        {
            // Application.CQRS is not visible from this compilation - nothing to generate here.
            return;
        }

        List<HandlerRegistration> commandHandlers = [];
        List<HandlerRegistration> queryHandlers = [];
        HashSet<INamedTypeSymbol> seen = new(SymbolEqualityComparer.Default);

        foreach (INamedTypeSymbol? candidate in candidates)
        {
            if (candidate is null || candidate.IsAbstract || !seen.Add(candidate))
            {
                continue;
            }

            foreach (INamedTypeSymbol iface in candidate.AllInterfaces)
            {
                if (iface.TypeArguments.Length != 2)
                {
                    continue;
                }

                if (SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, commandHandlerInterface))
                {
                    commandHandlers.Add(new HandlerRegistration(candidate, iface.TypeArguments[0], iface.TypeArguments[1]));
                }
                else if (SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, queryHandlerInterface))
                {
                    queryHandlers.Add(new HandlerRegistration(candidate, iface.TypeArguments[0], iface.TypeArguments[1]));
                }
            }
        }

        if (commandHandlers.Count == 0 && queryHandlers.Count == 0)
        {
            return;
        }

        context.AddSource("GeneratedDispatcher.g.cs", SourceText.From(GenerateDispatcher(commandHandlers, queryHandlers), Encoding.UTF8));
        context.AddSource("GeneratedCqrsRegistrations.g.cs", SourceText.From(GenerateRegistrations(commandHandlers, queryHandlers), Encoding.UTF8));
    }

    private static string GenerateDispatcher(List<HandlerRegistration> commands, List<HandlerRegistration> queries)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Cqrs.SourceGenerator - do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Application.CQRS;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Features.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Compile-time generated CQRS dispatcher - resolves and invokes handlers via a static");
        sb.AppendLine("/// type switch instead of runtime reflection.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class GeneratedDispatcher : IDispatcher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine("    public GeneratedDispatcher(IServiceProvider serviceProvider) => _serviceProvider = serviceProvider;");
        sb.AppendLine();

        AppendSendMethod(sb, "ICommand", "ICommandHandler", "command", commands);
        sb.AppendLine();
        AppendSendMethod(sb, "IQuery", "IQueryHandler", "query", queries);

        sb.AppendLine();
        sb.AppendLine("    // TResult and TActual are always the same closed type at each call site below - the switch");
        sb.AppendLine("    // case only matches when the handler's declared TResult matches the caller's TResult - so");
        sb.AppendLine("    // this cast is a safe reference-type coercion, not a reflective operation.");
        sb.AppendLine("    private static Task<TResult> Cast<TResult, TActual>(Task<TActual> task) => (Task<TResult>)(object)task;");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendSendMethod(StringBuilder sb, string messageInterface, string handlerInterface, string paramName, List<HandlerRegistration> handlers)
    {
        sb.AppendLine($"    public Task<TResult> Send<TResult>({messageInterface}<TResult> {paramName}, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine($"        switch ({paramName})");
        sb.AppendLine("        {");

        foreach (HandlerRegistration handler in handlers)
        {
            string messageType = handler.MessageType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string resultType = handler.ResultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine($"            case {messageType} typed:");
            sb.AppendLine($"                return Cast<TResult, {resultType}>(_serviceProvider.GetRequiredService<{handlerInterface}<{messageType}, {resultType}>>().Handle(typed, cancellationToken));");
        }

        sb.AppendLine("            default:");
        sb.AppendLine($"                throw new InvalidOperationException($\"No handler registered for {{{paramName}.GetType().Name}}\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static string GenerateRegistrations(List<HandlerRegistration> commands, List<HandlerRegistration> queries)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Cqrs.SourceGenerator - do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Application.CQRS;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Features.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Registers the generated CQRS dispatcher and every discovered command/query handler.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedCqrsRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddGeneratedCqrsHandlers(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.AddScoped<IDispatcher, GeneratedDispatcher>();");
        sb.AppendLine();

        AppendRegistrations(sb, "ICommandHandler", commands);
        AppendRegistrations(sb, "IQueryHandler", queries);

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendRegistrations(StringBuilder sb, string handlerInterface, List<HandlerRegistration> handlers)
    {
        foreach (HandlerRegistration handler in handlers)
        {
            string messageType = handler.MessageType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string resultType = handler.ResultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine($"        services.AddScoped<{handlerInterface}<{messageType}, {resultType}>, {handlerType}>();");
        }
    }

    private readonly struct HandlerRegistration
    {
        public HandlerRegistration(INamedTypeSymbol handlerType, ITypeSymbol messageType, ITypeSymbol resultType)
        {
            HandlerType = handlerType;
            MessageType = messageType;
            ResultType = resultType;
        }

        public INamedTypeSymbol HandlerType { get; }
        public ITypeSymbol MessageType { get; }
        public ITypeSymbol ResultType { get; }
    }
}
